# Autograd

- Given y = x**2 program to find the derivative of y w.r.t x 


In [1]:
def dy_dx(x):
    return 2*x

dy_dx(3)

6

- Given y = x**2 z=sin(y) program to find the derivative of z w.r.t x

In [2]:
import math

def dz_dx(x):
    return 2*x*math.cos(x**2)

In [3]:
dz_dx(2)

-2.6145744834544478

In [4]:
# using Autograd
# 1st question y =x**2

In [5]:
import torch

In [6]:
x = torch.tensor(3.0,requires_grad=True)

In [7]:
y =x**2

In [8]:
x

tensor(3., requires_grad=True)

In [11]:
y

tensor(9., grad_fn=<PowBackward0>)

In [12]:
y.grad_fn

In [13]:
y.backward()

In [14]:
x.grad

tensor(6.)

In [18]:
import math

def dz_dx(x):
    return 2*x*math.cos(x**2)
dz_dx(3)

-5.466781571308061

In [19]:
x =torch.tensor(3.0,requires_grad=True)
x

tensor(3., requires_grad=True)

In [20]:
y = x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [22]:
z =torch.sin(y)
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [23]:
z.backward()

In [24]:
x.grad

tensor(-5.4668)

In [27]:
y.grad

C:\Users\sibap\AppData\Local\Temp\ipykernel_1508\486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  y.grad


In [41]:
x =torch.tensor(6.7)
y =torch.tensor(0.0)

In [29]:
w =torch.tensor(1.0,requires_grad=True)
b =torch.tensor(0.0,requires_grad=True)

In [30]:
w

tensor(1., requires_grad=True)

In [31]:
b

tensor(0., requires_grad=True)

In [32]:
z =w*x +b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [33]:
y_pred =torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [39]:
def binary_cross_entropy(prediction,target):
    epsilon =1e-8
    prediction =torch.clamp(prediction,epsilon,1-epsilon)
    return -(target*torch.log(prediction)+(1-target)*torch.log(1-prediction))

In [42]:
loss = binary_cross_entropy(y_pred,y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [43]:
loss.backward()

In [44]:
print(w.grad,b.grad)

tensor(6.6918) tensor(0.9988)


In [45]:
# clearing Grad
x = torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [53]:
y =x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [54]:
y.backward()

In [55]:
x.grad

tensor(4.)

In [52]:
x.grad.zero_()

tensor(0.)

In [56]:
x.requires_grad_(False)

tensor(2.)

In [57]:
x

tensor(2.)

In [58]:
y =x**2
y

tensor(4.)

In [59]:
ar = torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [60]:
ar

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
# removing grad
new_ar =ar.detach()
new_ar

tensor([1., 2., 3.])

In [62]:
ar = torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [63]:
with torch.no_grad():
    y=ar**2
y

tensor([1., 4., 9.])