In [63]:
#importing torch
import torch

In [2]:
# python version
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
    print("gpu availale")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not availale using CPU")

gpu availale
Using GPU: NVIDIA GeForce RTX 3050 Laptop GPU


# Creating a Tensor

In [103]:
#using empty
x =torch.empty(2,3)
x

tensor([[-6.9448e-18,  9.6830e-43,  2.0803e-01],
        [ 1.1804e-01,  1.2169e-01,  7.3560e-01]])

In [104]:
type(x)

torch.Tensor

In [105]:
#zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [106]:
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [107]:
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [108]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [109]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [110]:
torch.tensor([[1,2,3,4],[1,2,3,4]])

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])

In [111]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [113]:
torch.linspace(1,10,12)

tensor([ 1.0000,  1.8182,  2.6364,  3.4545,  4.2727,  5.0909,  5.9091,  6.7273,
         7.5455,  8.3636,  9.1818, 10.0000])

In [114]:
torch.eye(10)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [115]:
torch.full((3,3),4)

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

In [116]:
bias =torch.full((3,3),-10)
bias

tensor([[-10, -10, -10],
        [-10, -10, -10],
        [-10, -10, -10]])

## Torch Shapes

In [117]:
x =torch.tensor([[1,2,3],[4,4,5]])

In [118]:
x.shape

torch.Size([2, 3])

In [119]:
x_like =torch.empty_like(x)
x_like

tensor([[1, 1, 1],
        [1, 1, 1]])

In [120]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [121]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [122]:

torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

Data Types

In [ ]:
x

tensor([[1, 2, 3],
        [4, 4, 5]])

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.0699, 0.3152, 0.2583],
        [0.3555, 0.1696, 0.0065]])

In [ ]:
x =torch.rand(2,2)
x

tensor([[0.0496, 0.9398],
        [0.3736, 0.0475]])

# Maths in torch

In [ ]:
# addition
print(x+2)
# sub
print(x-2)
# mul
print(x*2)
# div
print(x/2)
# int div
print((x*100)//2)
# int mul
print(((x*100)//2)%2)

tensor([[2.0496, 2.9398],
        [2.3736, 2.0475]])
tensor([[-1.9504, -1.0602],
        [-1.6264, -1.9525]])
tensor([[0.0991, 1.8796],
        [0.7472, 0.0950]])
tensor([[0.0248, 0.4699],
        [0.1868, 0.0238]])
tensor([[ 2., 46.],
        [18.,  2.]])
tensor([[0., 0.],
        [0., 0.]])


In [ ]:
x

tensor([[0.0496, 0.9398],
        [0.3736, 0.0475]])

In [ ]:
x*x

tensor([[0.0025, 0.8832],
        [0.1396, 0.0023]])

In [ ]:
x+x

tensor([[0.0991, 1.8796],
        [0.7472, 0.0950]])

In [ ]:
torch.round(x)

tensor([[0., 1.],
        [0., 0.]])

In [ ]:
torch.ceil(x)

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
torch.floor(x)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.clamp(x,min=2,max=3)

tensor([[2., 2.],
        [2., 2.]])

## inplace oporation

In [ ]:
m =torch.rand(2,3)
n =torch.rand(2,3)
print(m,n)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]]) tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])


In [ ]:
m.add_(n)

tensor([[0.9745, 0.8304, 0.6263],
        [1.0195, 1.1186, 1.4921]])

In [ ]:
m

tensor([[0.9745, 0.8304, 0.6263],
        [1.0195, 1.1186, 1.4921]])

In [ ]:
torch.relu(m)

tensor([[0.9745, 0.8304, 0.6263],
        [1.0195, 1.1186, 1.4921]])

## COPYing a Tensor

In [ ]:
a =torch.rand(2,4)

In [ ]:
b =a 
b

tensor([[0.2239, 0.3023, 0.1784, 0.8238],
        [0.5557, 0.9770, 0.4440, 0.9478]])

In [ ]:
a[0][0] =-1.3

In [ ]:
a,b

(tensor([[-1.3000,  0.3023,  0.1784,  0.8238],
         [ 0.5557,  0.9770,  0.4440,  0.9478]]),
 tensor([[-1.3000,  0.3023,  0.1784,  0.8238],
         [ 0.5557,  0.9770,  0.4440,  0.9478]]))

### using torch

In [ ]:
c = a.clone()

In [ ]:
c[0][0] = 3.6

In [ ]:
a,c

(tensor([[-1.3000,  0.3023,  0.1784,  0.8238],
         [ 0.5557,  0.9770,  0.4440,  0.9478]]),
 tensor([[3.6000, 0.3023, 0.1784, 0.8238],
         [0.5557, 0.9770, 0.4440, 0.9478]]))

## tensor operations  on GPU

In [4]:
torch.cuda.is_available()

True

In [5]:
device = torch.device("cuda")

In [7]:
torch.rand(2,3,device=device)

tensor([[0.2369, 0.6774, 0.4908],
        [0.9138, 0.6832, 0.0369]], device='cuda:0')

In [10]:
# moving existing tensor to GPU
a =torch.rand(2,3)
a

tensor([[0.7342, 0.1389, 0.9403],
        [0.6587, 0.7694, 0.9101]])

In [14]:
b =a.to(device)

In [15]:
b+5

tensor([[5.7342, 5.1389, 5.9403],
        [5.6587, 5.7694, 5.9101]], device='cuda:0')

In [17]:
import time

# Large size comparision test
size =10000

# two array
mat_cpu1 =torch.randn(size,size)
mat_cpu2 =torch.randn(size,size)

# Measuring time
start_time =time.time()
result_cpu =torch.matmul(mat_cpu1,mat_cpu2)
cpu_time =time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

#Move to GPU

mat_gpu1 =mat_cpu1.to(device)
mat_gpu2 =mat_cpu2.to(device)


start_time =time.time()
result_cpu =torch.matmul(mat_gpu1,mat_gpu2)
torch.cuda.synchronize() #Ensure all GPU oporation are complete
gpu_time =time.time() -start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

Time on CPU: 6.9139 seconds
Time on GPU: 1.0583 seconds


## Reshaping Tensors

In [18]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [24]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
b=torch.rand(3,2,4)
b

tensor([[[0.5082, 0.3978, 0.8785, 0.6250],
         [0.0357, 0.0926, 0.0708, 0.7081]],

        [[0.4857, 0.9859, 0.3255, 0.4778],
         [0.0842, 0.2385, 0.1819, 0.7938]],

        [[0.6617, 0.2127, 0.3384, 0.6877],
         [0.0401, 0.1484, 0.2837, 0.5390]]])

In [39]:
b.permute(2,0,1)

tensor([[[0.5082, 0.0357],
         [0.4857, 0.0842],
         [0.6617, 0.0401]],

        [[0.3978, 0.0926],
         [0.9859, 0.2385],
         [0.2127, 0.1484]],

        [[0.8785, 0.0708],
         [0.3255, 0.1819],
         [0.3384, 0.2837]],

        [[0.6250, 0.7081],
         [0.4778, 0.7938],
         [0.6877, 0.5390]]])

In [40]:
b.permute(2,0,1).shape

torch.Size([4, 3, 2])

In [44]:
# Unsquezze
c =torch.rand(226,226,3)
c

tensor([[[0.7306, 0.6640, 0.6105],
         [0.2113, 0.3760, 0.2165],
         [0.6428, 0.2014, 0.4867],
         ...,
         [0.6087, 0.1787, 0.9752],
         [0.9592, 0.0585, 0.6891],
         [0.7078, 0.1754, 0.5737]],

        [[0.8454, 0.0117, 0.7370],
         [0.4224, 0.3835, 0.7682],
         [0.5909, 0.0479, 0.1483],
         ...,
         [0.3620, 0.6398, 0.2883],
         [0.8088, 0.2568, 0.7436],
         [0.0010, 0.2008, 0.8167]],

        [[0.3778, 0.3156, 0.5084],
         [0.2113, 0.2023, 0.7501],
         [0.9035, 0.4623, 0.6544],
         ...,
         [0.7561, 0.7141, 0.7795],
         [0.4485, 0.7936, 0.6638],
         [0.6706, 0.2863, 0.3476]],

        ...,

        [[0.7989, 0.9530, 0.9566],
         [0.9983, 0.0759, 0.0421],
         [0.6383, 0.5650, 0.9859],
         ...,
         [0.7309, 0.3880, 0.3835],
         [0.0895, 0.0026, 0.7373],
         [0.5368, 0.1007, 0.5683]],

        [[0.3648, 0.0585, 0.3503],
         [0.2521, 0.7160, 0.0095],
         [0.

In [45]:
c.shape

torch.Size([226, 226, 3])

In [46]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [48]:
c.unsqueeze(0)

tensor([[[[0.7306, 0.6640, 0.6105],
          [0.2113, 0.3760, 0.2165],
          [0.6428, 0.2014, 0.4867],
          ...,
          [0.6087, 0.1787, 0.9752],
          [0.9592, 0.0585, 0.6891],
          [0.7078, 0.1754, 0.5737]],

         [[0.8454, 0.0117, 0.7370],
          [0.4224, 0.3835, 0.7682],
          [0.5909, 0.0479, 0.1483],
          ...,
          [0.3620, 0.6398, 0.2883],
          [0.8088, 0.2568, 0.7436],
          [0.0010, 0.2008, 0.8167]],

         [[0.3778, 0.3156, 0.5084],
          [0.2113, 0.2023, 0.7501],
          [0.9035, 0.4623, 0.6544],
          ...,
          [0.7561, 0.7141, 0.7795],
          [0.4485, 0.7936, 0.6638],
          [0.6706, 0.2863, 0.3476]],

         ...,

         [[0.7989, 0.9530, 0.9566],
          [0.9983, 0.0759, 0.0421],
          [0.6383, 0.5650, 0.9859],
          ...,
          [0.7309, 0.3880, 0.3835],
          [0.0895, 0.0026, 0.7373],
          [0.5368, 0.1007, 0.5683]],

         [[0.3648, 0.0585, 0.3503],
          [0.2521

In [54]:
# squeeze
d =torch.rand(1,20)
d

tensor([[0.4307, 0.4684, 0.2225, 0.1329, 0.1343, 0.6019, 0.7041, 0.2666, 0.1381,
         0.2288, 0.6772, 0.5916, 0.7243, 0.0219, 0.6274, 0.4454, 0.0533, 0.2391,
         0.1454, 0.4778]])

In [55]:
d.squeeze(0).shape

torch.Size([20])

In [56]:
d.squeeze(0)

tensor([0.4307, 0.4684, 0.2225, 0.1329, 0.1343, 0.6019, 0.7041, 0.2666, 0.1381,
        0.2288, 0.6772, 0.5916, 0.7243, 0.0219, 0.6274, 0.4454, 0.0533, 0.2391,
        0.1454, 0.4778])

In [57]:
import numpy as np

In [59]:
arr = np.random.rand(2,3)
arr

array([[0.13043041, 0.19103777, 0.81350471],
       [0.62422056, 0.45048435, 0.93577752]])

In [60]:
d.numpy()

array([[0.43067175, 0.4683792 , 0.22249156, 0.13294852, 0.13431716,
        0.60194737, 0.7041306 , 0.266603  , 0.1380642 , 0.22877479,
        0.6772386 , 0.59161955, 0.7242882 , 0.02192289, 0.6273981 ,
        0.44539165, 0.05328619, 0.23910928, 0.14543718, 0.47782063]],
      dtype=float32)

In [62]:
torch.from_numpy(arr)

tensor([[0.1304, 0.1910, 0.8135],
        [0.6242, 0.4505, 0.9358]], dtype=torch.float64)